---
driver:
  name: vagrant

provisioner:
  name: chef_zero
#  roles_path: '../roles'

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.2

suites:
  - name: default
    run_list:
#       - role[webserver]
      - recipe[i::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
